# Generated by Django 3.2.13 on 2022-07-14 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(max_length=40, null=True)),
                ('month', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=200)),
                ('userEmail', models.EmailField(max_length=500)),
                ('birthday', models.DateField(null=True)),
                ('contact', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=25)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(default='Coimbatore', max_length=100, null=True)),
                ('state', models.CharField(default='Tamil Nadu', max_length=100, null=True)),
                ('pincode', models.CharField(max_length=8)),
                ('occupation', models.CharField(default=None, max_length=50)),
                ('workingHours', models.IntegerField()),
                ('bloodGroup', models.CharField(default=None, max_length=10)),
                ('sleepingTime', models.CharField(default=None, max_length=20)),
                ('emergencyContact', models.CharField(default=None, max_length=100)),
                ('trainingMode', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online')], default='offline', max_length=20)),
                ('isMember', models.BooleanField(default=False, null=True)),
                ('height', models.CharField(max_length=25)),
                ('weight', models.CharField(max_length=25)),
                ('attendedGym', models.CharField(default='no', max_length=5)),
                ('BPCheck', models.CharField(blank=True, default=None, max_length=40)),
                ('question1', models.CharField(default=None, max_length=5)),
                ('question2', models.CharField(default=None, max_length=5)),
                ('question3', models.CharField(default=None, max_length=5)),
                ('smokingHabit', models.CharField(default=None, max_length=20)),
                ('question4', models.CharField(default=None, max_length=5)),
                ('question5', models.CharField(default=None, max_length=5)),
                ('physicalActivity', models.CharField(default=None, max_length=25)),
                ('exerciseFrequency', models.CharField(default=None, max_length=25)),
                ('exerciseDuration', models.CharField(default=None, max_length=25)),
                ('question6', models.CharField(default=None, max_length=5)),
                ('fitnessGoal', models.CharField(default=None, max_length=100)),
                ('memberId', models.CharField(max_length=20, null=True, unique=True)),
                ('package', models.CharField(max_length=20, null=True)),
                ('startDate', models.DateField(default=None, null=True)),
                ('endDate', models.DateField(null=True)),
                ('fees', models.IntegerField(default=None)),
                ('BMI', models.CharField(max_length=10, null=True)),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to='static/images_uploaded')),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
